using Microsoft.EntityFrameworkCore;
using MyBackend.Application.Common.Exceptions;
using MyBackend.Application.Common.Interfaces;
using MyBackend.Application.Contracts;
using MyBackend.Application.Interfaces;
using MyBackend.Domain.Entities;
using System.Text;
using System.Text.Json;

namespace MyBackend.Application.Services
{
    public class ReportService : IReportService
    {
        private readonly IApplicationDbContext _context;

        public ReportService(IApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<ReportsOverviewResponse> GetReportsAsync(string? category, string? search)
        {
            var query = _context.Reports
                .Where(r => r.DeletedFlag == 1)
                .AsNoTracking();

            if (!string.IsNullOrWhiteSpace(category) && category != "ALL")
            {
                query = query.Where(r => r.Category.ToLower() == category.ToLower());
            }

            if (!string.IsNullOrWhiteSpace(search))
            {
                var lower = search.ToLower();
                query = query.Where(r => r.Title.ToLower().Contains(lower) ||
                                         r.Description.ToLower().Contains(lower) ||
                                         r.Category.ToLower().Contains(lower));
            }

            var reports = await query.OrderByDescending(r => r.Id).ToListAsync();

            var totalReports = await _context.Reports.CountAsync(r => r.DeletedFlag == 1);
            var readyReports = await _context.Reports.CountAsync(r => r.DeletedFlag == 1 && (r.Status == "Ready" || r.Status == "Generated"));

            return new ReportsOverviewResponse
            {
                ReportsGenerated = totalReports,
                ExportsReady = readyReports,
                RoleCoverage = "100%",
                Reports = reports
            };
        }

        public async Task<List<string>> GetCategoriesAsync()
        {
            var defaultCategories = new List<string> { "Compliance", "Security", "Role Mapping", "Access Audit", "User Directory", "Financial Audit", "Governance" };
            var dbCategories = await _context.Reports
                .Where(r => r.DeletedFlag == 1 && !string.IsNullOrWhiteSpace(r.Category))
                .Select(r => r.Category)
                .Distinct()
                .ToListAsync();

            return defaultCategories.Union(dbCategories).Distinct().ToList();
        }

        public async Task<ReportDownloadResult?> GetReportDownloadAsync(int id)
        {
            var report = await _context.Reports.FirstOrDefaultAsync(r => r.Id == id && r.DeletedFlag == 1);
            if (report == null) return null;

            var format = (report.Format ?? "PDF").ToUpper();
            if (format == "JSON")
            {
                var jsonContent = JsonSerializer.Serialize(new
                {
                    report.Id,
                    report.Title,
                    report.Category,
                    report.Description,
                    report.Format,
                    report.CreatedBy,
                    report.CreatedAt,
                    ExportTimestamp = DateTime.UtcNow,
                    System = "Enterprise RBAC Platform",
                    Status = "Certified"
                }, new JsonSerializerOptions { WriteIndented = true });

                return new ReportDownloadResult
                {
                    FileBytes = Encoding.UTF8.GetBytes(jsonContent),
                    ContentType = "application/json",
                    FileName = $"{report.Title.Replace(" ", "_")}.json"
                };
            }
            else if (format == "CSV")
            {
                var csv = $"Id,Title,Category,Format,CreatedBy,CreatedAt,Status\n{report.Id},\"{report.Title}\",\"{report.Category}\",\"{report.Format}\",\"{report.CreatedBy}\",\"{report.CreatedAt:yyyy-MM-dd HH:mm:ss}\",\"Certified\"\n";
                return new ReportDownloadResult
                {
                    FileBytes = Encoding.UTF8.GetBytes(csv),
                    ContentType = "text/csv",
                    FileName = $"{report.Title.Replace(" ", "_")}.csv"
                };
            }
            else
            {
                var doc = $"=====================================================\n" +
                          $"               COMPLIANCE AUDIT REPORT               \n" +
                          $"=====================================================\n" +
                          $"Title:       {report.Title}\n" +
                          $"Category:    {report.Category}\n" +
                          $"Generated By:{report.CreatedBy}\n" +
                          $"Date:        {report.CreatedAt:yyyy-MM-dd HH:mm:ss UTC}\n" +
                          $"Status:      Verified & Certified\n" +
                          $"-----------------------------------------------------\n" +
                          $"Executive Summary & Audit Scope:\n" +
                          $"{report.Description}\n" +
                          $"=====================================================\n";
                return new ReportDownloadResult
                {
                    FileBytes = Encoding.UTF8.GetBytes(doc),
                    ContentType = "text/plain",
                    FileName = $"{report.Title.Replace(" ", "_")}.txt"
                };
            }
        }

        public async Task<Report> CreateReportAsync(CreateReportRequest request, string creatorName)
        {
            if (string.IsNullOrWhiteSpace(request.Title))
            {
                throw new BadRequestException("Report title is required.");
            }

            var report = new Report
            {
                Title = request.Title.Trim(),
                Description = request.Description.Trim(),
                Category = string.IsNullOrWhiteSpace(request.Category) ? "Compliance" : request.Category.Trim(),
                Format = string.IsNullOrWhiteSpace(request.Format) ? "PDF" : request.Format.Trim(),
                CreatedBy = creatorName,
                Status = "Ready",
                FileSize = "1.5 MB",
                CreatedAt = DateTime.UtcNow,
                DeletedFlag = 1
            };

            _context.Reports.Add(report);
            await _context.SaveChangesAsync();
            return report;
        }

        public async Task<Report?> UpdateReportAsync(int id, UpdateReportRequest request)
        {
            var report = await _context.Reports.FirstOrDefaultAsync(r => r.Id == id && r.DeletedFlag == 1);
            if (report == null) return null;

            report.Title = request.Title.Trim();
            report.Description = request.Description.Trim();
            report.Category = request.Category.Trim();
            report.Format = request.Format.Trim();
            report.Status = string.IsNullOrWhiteSpace(request.Status) ? report.Status : request.Status.Trim();

            await _context.SaveChangesAsync();
            return report;
        }

        public async Task<bool> DeleteReportAsync(int id)
        {
            var report = await _context.Reports.FirstOrDefaultAsync(r => r.Id == id && r.DeletedFlag == 1);
            if (report == null) return false;

            report.DeletedFlag = 0;
            await _context.SaveChangesAsync();
            return true;
        }
    }
}
